---
title: "Workshop 4"
output: html_document
date: "2025-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


R can be used as a GIS. Useful because of version controls, can save a script, can interface with other R uses like ggplot, and it is free.

# Installing the spatial R packages

```{r}
# install.packages("sf") 
# install.packages("terra")
# install.packages("tmap")


#load into R library
library(tidyverse)
library(sf) # simple features
library (terra) # for raster
library(tmap) # Thematic maps are geographical maps in which spatial data distributions are visualized
```

# Downloading and loading the spatial dataset

```{r}
#load the copepod data into R studio
library(readr)
dat <- read_csv("../data/data-for-course/copepods_raw.csv")
dat
```

# Data exploration

# Check coordinates

```{r}
library(ggplot2)
ggplot(dat) + 
  aes(x = longitude, y = latitude, color = richness_raw) +
  geom_point()
```
Look at species richness in a non-spatial way
```{r}
ggplot(dat, aes(x = latitude, y = richness_raw)) + 
  stat_smooth() + 
  geom_point()
```


